# Chapter 7 - Conclusion

This concluding chapter seeks to bring the preceding six chapters of this dissertation together. The goals of this chapter are four-fold: first, to summarize what this dissertation has shown; second, to identify what this dissertation has not yet shown; third, to help the reader understand what this study means and why it matters, especially with respect to contemporary civil-military relationships in the United States; and fourth, to recommend avenues of future research.

This chapter proceeds in four main parts. The first part of the chapter briefly integrates the overall argument and the findings presented over the previous six chapters. This part of the chapter is intended to succinctly capture what this dissertation has shown. The second part of this chapter identifies important limitations of this study, and discusses important aspects of the argument that are not yet known. The third portion of this chapter presents the implications of this dissertation. Emphasis is placed on why scholars, military officers, and the American public should care about what has been presented here in this dissertation. The final part of the chapter recommends several strands of future research related to this dissertation.   

## Integrating the Argument

At its core, this dissertation ultimately sought to explain why political behaviors involving the military occur in mature democracies such as the United States. In so doing, this dissertation first provided a framework by which to assess and measure political behaviors involving the military. The framework presented here centered on the adherence by civilian and military actors to three central principles of civil-military relations. In chapter one, these were exposited and identified as the principles of civilian control of the military, non-partisanship of the military institution, and non-interference of the military into certain realms of the state. These principles have their roots in scholars such as Samuel Huntington, his critics, and military normative practices that have been fostered since at least the end of World War Two. 

Chapter two then presented a theory that argued that two primarily domestic variables, the levels of military prestige and political polarization, shape the degree to which civilian and military actors adhere to these principles. The theory argued that military actors increasingly violate the central principles of civil-military relations as the levels of both political polarization and military prestige rise. Civilian actors, the theory argued, increasingly violate the principles of civil-military relations as the level of military prestige rises. The theory also argued that because these domestic variables always exist at some level, the two variables combine such that four distinct domestic structures are ultimately plausible, each of which denotes paired relative (high or low) values of the level of political polarization and military prestige. These domestic structures, furthermore, broadly describe which actor type induces polarization, what level of political activity occurs, and what degree of potential for civil-military conflict exists, in each structure. These domestic structures can be seen in Table \@ref(tab:poss-environment3).

Chapters three through six tested this theory. Chapters three and four performed rigorous and original quantitative analyses of observational data of one political behavior undertaken by each separate type of actor. Chapter three explored public appeals written by retired military officers (a military actor) from 1979-2020, and chapter four explored the use of military imagery and military actors in presidential campaign advertisements from 2000 - 2016, a behavior undertaken by predominantly civilian actors. 

The methodological approach employed in chapters three and four was similar. I first operationalized how each type of behavior might violate each central principle of civil-military relations in practice. I then identified these violations across the data, controlled for other variables that might also be responsible for spurring these violations, and analyzed the data over time, and in chapter four, also across space (geographic media markets in the United States).    

Chapters five and six, on the other hand, investigated the theory through qualitative analysis. These chapters, too, employed a similar methodological approach. Each chapter examined a different historical era in which one of the two independent variables (military prestige and polarization) changed, while the other variable remained relatively constant. Chapter five went back to the 19th Century, and examined the roughly 15 year period from the end of the US Civil War in 1865 until 1880. During this period, the level of polarization remained high, but the level of military prestige declined. Chapter six examined the contemporary post-9/11 era. During the twenty years from 2001 - 2021, the level of military prestige remained relatively high and constant, but the level of polarization in the United States rose significantly.

The methodological approach employed in both chapters five and six was different than that undertaken in chapters three and four. Instead of examining one political behavior undertaken by one type of actor, chapters five and six sought to examine multiple political behaviors undertaken by both types of actors, and to characterize the tone, tenor, and broader characteristics of the political activity involving the military undertaken in each era. 

In order to do this, each chapter examined major episodes or events that occurred within each of the periods of time examined in each chapter. For instance, chapter five compared and contrasted political behavior involving the military undertaken in 1865-1868 with that undertaken in 1877-1880. Chapter six, on the other hand, compared and contrasted the "Revolt of the Generals," which was undertaken in 2006, with political activity involving the military undertaken amid unfolding domestic unrest in 2020 and immediately after the US withdrawal from Afghanistan in 2021. 

### Findings and Results

### The Roles of Polarization and Military Prestige

This dissertation clearly found that rising levels of polarization impact the degree to which military actors adhere to the three central principles of civil-military relations. Chapter three found moderate statistical evidence for this assertion (see in particular Tables \@ref(tab:ch3reg1) and \@ref(tab:ch3reg2) ). The first period examined in chapter five  (1865-1868) as well as the second portion of chapter six (2020-2021) also found qualitative evidence highly consistent with this claim. As the level of polarization rises, the results consistently suggest that military actors are increasingly willing to violate the principles of civil-military relations. 

Chapters five and six especially found evidence consistent with the underlying reason for this relationship between rising polarization and a weakening adherence to the central principles of civil-military relations by military actors. The theory argued that high polarization levels indicate the presence of significant divergence, and potentially fundamental opposition, in the political community concerning the underlying moral values and worldviews that hold sway in the state. During the post-US Civil War period, the fundamental opposition in moral values and worldviews centered on issues comprising American Reconstruction policy. Among these issues, chapter five noted, were the immense questions related to the rights and political freedoms of former slaves, what actions the federal government should take to secure these freedoms, and what punitive measures, if any, should be levied against the former Confederate states and those who had taken up arms against the Union. In chapter six, this divergence in moral values and worldviews underlying high levels of polarization levels stemmed from disagreement concerning multiple policies of the former President, Donald Trump, and what underlying values these policies stood for. 

Evidence for the level of military prestige shaping the political behavior of military and civilian actors is not quite as strong as the evidence for the level of polarization. Chapter four found evidence that civilian actors are in fact sensitive to the level of military prestige in employing or harnessing military figures to appear and to behave in certain ways that violate the central principles of civil-military relations during presidential campaign television advertisements. However, chapter four employed a proxy measurement for the level of military prestige (the percentage of the overall population that is a veteran in each media market). By itself, the use of a proxy measurement in chapter four is not necessarily problematic. However, and as chapter four noted, there are other possible variables that might also be correlated with the percentage of the veteran population in a particular locale, such as partisanship or military culture, that prevent firmly drawing the conclusion that military prestige (as measured by the proxy of the percentage of veterans in the population) is in fact driving civilian actors to employ military figures in campaign ads in ways that violate the central principles of civil-military relations. 

Still, the evidence for the role of military prestige in shaping civilian and military actor adherence to the central principles of civil-military relations was more than merely anecdotal. In particular, the case study undertaken in chapter five suggested that even when high polarization levels abound - as they did throughout the bulk of the late 19th Century in the US - a relatively less prestigious military does not hold as much potential to influence public opinion, and that as a result, military and civilian actors are less likely to behave in ways that violate the principles of civil-military relations when the level of military prestige is relatively low compared to when it is high.  

### The Presence of Unique Domestic Environments that Shape Civil-Military Relations

Holistically, there is mild evidence to support the notion that there are distinct domestic environments that exist and which depend on the relative levels of political polarization and military prestige. At a minimum, this stands out as a contribution that will help future scholars and practitioners of civil-military relations in terms of appreciating and articulating the similarities and differences of the conduct of civil-military relations over time. Of the four theoretical domestic environments that are shown in Table \@ref(tab:poss-environment3), however, the one that was not explored in depth in this dissertation is that which is possible when both polarization and military prestige operate at relatively low levels. 

However, this dissertation explored the presence of these environments in strictly relative terms. This enabled clearer theoretical distinctions to be drawn between environments. For now, this is the best way to think about and employ this framework, rather than to insist that a certain era falls into a distinct quadrant in an absolute sense.   

## Limitations of this Study

While I have attempted to undertake a systematic and careful investigation of the role of polarization and military prestige in shaping the political activity of civilian and military actors involving the military, there are nonetheless several shortcomings that deserve highlighting. 

### Methodological Approach

One of the main limitations of this study involves the methodological approach undertaken, particularly in chapters three and four, the main quantitative empirical chapters of the dissertation. As with most studies that rely on observational data, there are always concerns about omitted variables and endogeneity. This study is no exception. Though some of these concerns were addressed back in chapter two, it is worth making a couple of additional statements now that the empirical analyses are complete. 

In each of the empirical chapters (3 and 4), the respective regression analyses included controls for variables that theoretically could also have driven variation in the dependent variables examined. Though this is standard practice for regression analyses with observational data, omitted variable bias always presents some level of concern, as the preceding discussion of the proxy measurement of military prestige in chapter four made clear. Furthermore, while the two historical case studies added a level of richness that provided scholarly benefit, doing so introduced a whole host of potential omitted variables. Indeed, much has changed in American society besides the levels of polarization and military prestige in the 156 years between 1865 and 2020, the beginning of the first case study and the end of the second.   

For this reason, it is best to see this dissertation as having established a general relationship between the independent variables of polarization and military prestige and the dependent variable of political acts that violate principles of civil-military relations, rather than a causal relationship. In other words, this dissertation does not allow us to conclude that polarization or military prestige _cause_ military and civilian actors to behave in certain ways. But we can conclude that these variables are _associated_ with these actors adhering to the principles of civil-military relations to differing degrees and in somewhat predictable ways. This is still an important and original finding.  

### Theoretical Approach

Another limitation of this study involves the theory advanced in this dissertation. The theory advanced in this dissertation deliberately incorporated _both_ military and civilian actors. Doing so, chapters one and two argued, is both a better reflection of the two-sided nature of civil-military relations and the reality that both types of actors play significant roles in sustaining a state's overall civil-military relationship.

While this is an overall positive theoretical undertaking, the one actor that did not receive more articulation in the theory is the public itself. The role of the public in the theory advanced here was implicit; that is, this theory noted how the variables of polarization and military prestige impact various aspects of the public. For example, this dissertation noted that rising polarization is associated with the public being more divided over issues of the day, and that the level of military prestige impacts public opinion regarding the military in certain ways. 

Future theoretical refinements to the theory advanced in this dissertation might more explicitly separate the public as an altogether separate actor, however, from the civilian and military elites who regularly engage in the conduct of civil-military relations. Doing so may enable even more finely grained examinations of the variables of polarization and military prestige, and in particular, _how_ these variables impact the public, and in what ways. 

On a related note, this dissertation viewed the variables of military prestige and polarization as truly conceptually independent from each other. For the specific empirical data and the case studies examined in this dissertation, this theoretical distinction between the variables of military prestige and polarization was, for the most part, logical and sound. At the same time, the case studies in particular brought out the fact that the partisan identification of members of the public impacts how these members view the military, especially during periods of high polarization. 

For example, the case study undertaken in chapter six pointed out that Republicans in particular were those who called on General Milley to resign in 2021 following the US withdrawal from Afghanistan and revelations of him engaging in phone calls with a Chinese General and with the Speaker of the House. Additionally, chapter five pointed out that Southern Democrats were especially viewed the military in a negative light as a result of the military's involvement in American Reconstruction in the late 1860s and 1870s. 

Thus, there is evidence that in fact, the variables of polarization and military prestige are not entirely independent from each other, at least under some range of extreme values of polarization. One way of dealing with this issue in future research involves, as the preceding paragraphs suggest, undertaking studies which separate the public by party affiliation. Indeed, contemporary studies of public opinion involving the military seem to be doing just this [@hadley_afghanistan_2021].

### Generalizability

Another significant limitation of this study involves the issue of generalizability. Here, there are two distinct challenges. The first involves the degree to which this dissertation's findings export to settings beyond the United States, and the second involves the degree to which some of the findings export within the United States. 

First, this dissertation clearly centered on the United States. Yet all of the variables contained in the theory operate and exist in settings beyond the United States. Thus, an important question is whether the findings uncovered in this dissertation might also apply, and to what degree, in other mature democracies, such as in Canada, Western Europe, and Israel? The short answer is that we cannot be entirely sure. Future research can and should incorporate cross-national investigations of elements of the theory presented in this dissertation. Nonetheless, a couple of considerations are important. 

One important consideration related to the generalizability of the theory advanced here to other mature democracies involves the definition and the underpinnings that are associated with the independent variables. In particular, the variable of polarization may contain several US-specific considerations. This dissertation, for instance, conceptualized polarization to indicate the degree of divergence in the moral values that hold sway in society. And while the definition of polarization may be the same in other contexts beyond the US, it is not clear, at least to me, that polarization necessarily reflects the same dynamic of divergence in moral values and/or worldviews that are competing for primacy in the public square in other countries. 

This matters because using US-specific measures of polarization, such as DW-NOMINATE scores used in chapter three and shown in multiple places throughout this dissertation, the United States has only had extreme levels of polarization twice in its history. Scholars of comparative politics and country-specific experts will perhaps be in a better position to determine if polarization is a relatively unique (or not) phenomenon in a particular country or region of interest. Intuitively, my initial guess is that in countries where polarization is or has been far more common than in the United States, changes in the level of polarization would result in far less significant change in the dependent variable than have been uncovered here. But again, this is only a conjecture that future research would have to tackle conclusively. 

Another important consideration with respect to generalizing the findings of this dissertation to other mature democracies involves the dependent variable of political activity that violates the principles of civil-military relations. The three central principles of civil-military relations that were derived in chapter one of this dissertation likely apply in other mature democracies. But a difficulty arises when we try to define the scope and boundaries of these three central principles in settings beyond the US. Doing so will require some alteration on the part of country-specific and regional experts.  

For example, I noted in chapters two, three, and six that in the United States, the line that separates active from retired military officers, and the conduct that each group of military actors undertakes, is real but has historically not been drawn in drastically different places (although this dissertation argued that this line is being increasingly drawn in different places as a result of increasing polarization!). However, it is not clear to me that such a line either exists, nor that it must necessarily exist, in other countries, including in mature democracies. Retired military officers in, for example, France may act very different from the collective body of retired military officers in the United States, and thus, analyzing Retired French military officer opinion commentary, as undertaken here in chapter three for American retired officers, may not serve as the best way of measuring how military actors in France might violate the principles of civil-military relations.  

It is therefore important to at least allow room for the possibility that while all mature democracies broadly share the three central principles of civil-military relations, how these principles have historically regulated specific instances of political behavior may require country-specific application and interpretation. For example, violation of the principle of non-partisanship in the two party system of the United States is a somewhat clear violation to identify, in my view. I am not as certain about how the principle of non-partisanship should look in practice in parliamentary systems of government, where multiple parties exist.

A second issue that pertains to generalizability involves other political behaviors involving the military in the United States that were not explored in this dissertation. In other words, I focused on one and only one type of political behavior in chapters three and four utilizing observational data. Because there are multiple types of political behaviors that civilian and military actors have at their disposal (see Tables \@ref(tab:pol-behav) and \@ref(tab:pol-behav-civ)), one criticism might be that the results uncovered here thus apply only to these particular behaviors. 

My response to this particular thread of criticism is one of agreement: indeed, we cannot state that the levels of polarization and military prestige will, for sure, be associated with increasing violations of the principles of civil-military relations through every and all other types of political behaviors undertaken by military and civilian actors, respectively. Nonetheless, this research project has undertaken the first rigorous and original analysis of these two behaviors specifically that future scholarship can and should build on. 

## Implications of this Study

This section presents the main implications of this dissertation. Here, I have in mind what I think are the most important takeaways for policymakers, especially civilian and military elites, with respect to the conduct of civil-military relations in the contemporary United States. 

### The Domestic Environment Matters 

The first implication stemming from this dissertation is that the state's domestic environment profoundly shapes civil-military relations. This is true because the domestic environment shapes the behavior of civilian and military actors. At a minimum, civilian and military actors can and should recognize how each type of actor responds to changes in the levels of military prestige and polarization, and how these changes have unfolded in different eras in US history. Such recognition likely will not make the conduct of civil-military relations for either type of actor necessarily easier, but it will enable each type of actor to better understand the inherent pull that each actor type is subject to in the political arena. 

This dissertation suggests that civilian actors will inherently be pulled by the desire to win and remain in political office, a finding that is consistent with the most basic of political instincts. A highly prestigious military that has the potential to influence and shape public opinion is thus a ripe target for civilian actor efforts to harness the military for their own advantage. This dissertation did not empirically test whether military actors too are sensitive to changes in the level of military prestige, but the theory presented here suggests that they are, as does the qualitative evidence presented in chapter five. 

In short, both civilian and military actors are increasingly likely to use the military, when it is relatively prestigious, in ways that challenge and in some cases, violate, the principles of civil-military relations. Military and civilian actors may not be particularly surprised by this implication, but both actor types should acknowledge the reality of this tendency. This dissertation also found that military actors are particularly sensitive to changes in the level of political polarization in the state. In particular, rising levels of polarization indicate that military actors will increasingly behave in ways that violate the central principles of civil-military relations. The major takeaway from this finding, in my view, differs for civilian and military leaders, respectively.

Civilian leaders who govern during times of high polarization should recognize that the military is not insulated from the pernicious effects of polarization. Especially as the issues that comprise a state's polarized political landscape involve matters that address issues that involve moral values, the military and its members are increasingly likely to be divided in an ideological sense. While I do not think that civilian leaders should necessarily lower their expectations in terms of expecting professional conduct from the military in polarizing times, civilian leaders should recognize these forces that underlie the dynamics of polarization as significant.

Military leaders should also understand that they face unique challenges in polarizing times, much in the way that Generals Grant (in chapter five) and Milley (in chapter six) seem to have understood in terms that were up close and personal to each of them. These challenges are especially pronounced when both polarization and military prestige exist simultaneously at high levels. 

The challenge military leaders face in eras of high polarization and relatively high military prestige is thus two fold. The first involves the challenge that senior military leaders face in dealing with their civilian actor counterparts and superiors in polarizing times. Polarizing times are inherently associated with controversial policies that are, by definition, hated by some and beloved by others. This naturally places military leaders, especially those who operate at the highest levels, in a tough place with little room to wiggle, politically speaking. Even military leaders who initially eschew partisan identification at all costs, it seems, eventually encounter a situation in which they either reluctantly ally with a partisan group, or are labeled an ally of a partisan group. In chapter five, this occurred when General Grant eventually allied with Republicans in Congress as a means of preventing President Johnson from doing what Grant and the Republicans thought would be irreparable damage to the Republic as Reconstruction proceeded, and in chapter six, when several Republicans accused Milley of being a traitor for engaging in phone calls with a Chinese General in the wake of the 2020 Presidential Election and its aftermath. 

The second challenge that military leaders face in highly polarizing environments involves their ability to lead, manage, and harness their own internal military organizations and members. These organizations and members include primarily those who serve on active duty, but also those military retirees, veterans, and other veteran-affiliated groups that can also be considered as military actors. As this dissertation has noted several times, members of the military are likely to be polarized when the nation is polarized. Military leaders cannot be blind or deaf to this reality, and at the same time, senior military leaders should insist that their organizations and members act professionally and thus, adhere to the central principles of civil-military relations. 

Thus, the second challenge of leading in polarizing times presents somewhat of a tightrope for military leaders to walk in practice. If military leaders ignore the reality and the strength of polarization, their lack of action might be interpreted by their own populations and members as favoring one political or partisan side or the other over any number of polarizing issues. On the other hand, if military leaders do not insist on professional conduct - even in the midst of ongoing tensions that reflect polarization - they risk the military and its members also being seen as favoring or allying with one side over the other.  

\singlespace
### The Principles of Civil-Military Relations Require a Healthy Environment to Flourish
\doublespace

A second implication stemming from this dissertation involves the conditions that lead to the nurturing and sustainment of the central principles of civil-military relations in the United States. Simply put, this dissertation's findings suggest that the central principles of civil-military relations flourish better under some domestic conditions rather than others. 

To state this another way, the United States seems to have developed the central principles of civil-military relations because certain domestic conditions enabled their formulation, adoption, and inculcation. This seems to at least fit with the fact that Samuel Huntington wrote _The Soldier and the State_ in 1957, a period during which the level of polarization in the United States was more or less in the middle of a 40 year long relative low that spanned from the mid-1930s until the mid-1970s, as shown in Figure \@ref(fig:polar-chamber). That Huntington did not write about polarization is not necessarily oversight on his part. He did not need to account for polarization because it was not a major concern at the time. We simply live in different times, however. 

Huntington does not explicitly talk about the variable of military prestige, but this variable is implicit in much of Huntington's work. Indeed, he is writing at a time when the US military is fairly prestigious, as it plays a crucially important role in the Cold War with the Soviet Union after World War Two. American history is full of examples of civil-military disputes that occurred when polarization was relatively low and when military prestige was relatively high. These include disputes that occurred between President Truman and General Douglas MacArthur over Korea in 1951, President Eisenhower and General Matthew Ridgeway over Ike's New Deal policies in the early 1950s, and even the "Revolt of the Generals" between Secretary Rumsfeld and several retired generals in 2006 (discussed in chapter six of this dissertation). All of these were substantial disputes that constituted genuine crises in American civil-military relations. 

But other civil-military relations crises have occurred against a far more serious backdrop. Those that have occurred under simultaneously high conditions of military prestige and polarization, such as between Grant and Johnson in 1867-1868, and between some retired generals and President Trump in 2020 as well as some members of Congress and General Milley in 2021, are even more severe. 

In these types of crises, when polarization is at an extreme level, a popular military may find itself involved in disputes that involve the political fabric of the state. Against such a backdrop, Presidents are impeached, as they were in 1868, 2019, and 2021. Election results are disputed, as they were in 1876 and in 2020. The Constitution itself is questioned. This dissertation thus ultimately points to the conclusion that when the democracy itself is threatened internally - as a result of polarization - the state's military cannot avoid this reality. 

I will allow the political theorists to intelligently debate about the conditions that most endanger democracy, but even a cursory examination of this dissertation suggests that these conditions exist when the definition of what is morally right in society is no longer shared. Certainly, how this manifests itself in a particular period of time will undoubtedly be different, depending on any number of specific polarizing issues and other factors. 

Allen Guelzo, a prominent historian, tells the story of how Abraham Lincoln, not yet a Senator, began to debate Stephen Douglas in 1854 on the pending Kansas-Nebraska Act, which allowed settlers to exercise the democratic right of "popular sovereignty" to decide whether slavery should be extended into these territories [@guelzo_abraham_2010, 187]. Lincoln, Guelzo notes, was certainly not an abolitionist, but began to feel that the spread of slavery and the democratic right of popular sovereignty were utterly incompatible. Lincoln would strongly condemn Douglas and his support of the doctrine of popular sovereignty on the grounds that, "it assumes that there can be MORAL RIGHT in the enslaving of one man by another" [Lincoln, 1854 quoted in @guelzo_abraham_2010, 187].

We certainly do not live in the same times. But a number of other issues addressed throughout this dissertation, ranging from what it means to be an American, to whether parents should have a say in what their kids are taught in school, all touch on moral values.  

Military prestige and polarization thus each pose unique challenges for civilian and military actors. Neither one should be ignored or brushed aside. But of the two, polarization seems to be the more severe because of what it signifies and thus, its obstinacy and staying power. Changes in the level of military prestige certainly do not change overnight. It took the military nearly two decades to rebuild after Vietnam [@kitfield_prodigal_1997]. Even so, there have been spikes in the level of military prestige that occur over much shorter periods of time, perhaps none so prominent as that which occurred following the Gulf War in 1991 (see Figure \@ref(fig:polar-trust-oped)). 

Polarization, on the other hand, seems to stay around for a while. As shown in Figure \@ref(fig:polar-chamber) and discussed in chapter five of this dissertation,the only other period of time in US history marked by very high levels of polarization involved the late-19th Century until the early 20th Century (around 1904). Although formal measurements of polarization are available beginning in the 1880s, we can reasonably assume that this period of high polarization started sometime before the Civil War. If we mark this period of high polarization very conservatively at 1860, this means that the nation was highly polarized for more than four decades. We cannot predict the future with certainty, but a solemn appreciation for the dynamic of polarization suggests that current levels of polarization in the US are not likely to easily or suddenly abate. 

For this reason, military leaders in particular should study American civil-military relations in the post-US Civil War period, if for no other reason to gain an appreciation of the tremendous difficulties and challenges that leaders such as General Ulysses Grant encountered. No historical period is the same as another, but there is still much that can be learned. Grant is perhaps best known for his martial exploits during the Civil War, but at this particular moment in US history, one can make the argument that it is his experiences after the Civil War in dealing with Congress, the President, and a divided Republic that are especially applicable to the challenges that military leaders face while operating during polarizing times. 

## Avenues of Future Research

There are several strands of future research this dissertation can and should spur. The first involves the degree to which the theory advanced in this dissertation applies to democracies beyond the United States. Scholars should conduct cross-national or country-specific investigations using the framework and the theory that have been advanced here, even if doing so requires slight modifications. These modifications need not necessarily alter the theory to such a point where it is no longer recognizable. Country specific experts, for instance, can identify what form of political behaviors involving the military constitute violations to each of the central principles of civil-military relations, and develop similar strategies as employed in this dissertation to measure these behaviors.

Future scholarship should also undertake further examinations of the role of military prestige in shaping adherence to the principles of civil-military relations, especially in the US context. In this dissertation, doing this proved to be somewhat tricky, largely because of the limitations of the data explored in chapter four (as discussed above). One way to approach this shortfall might involve undertaking cross-national examinations in contexts that have witnessed far-greater variation in military prestige than the United States. 

Another way to investigate this question could involve in-depth examinations in the US context, but in different cases than were examined here in this dissertation. One case in particular that seems ripe for investigation is the political behavior involving the military immediately after (and perhaps even during the end of) the Vietnam War, in the early-mid 1970s. This dissertation suggests that if the prestige of the military dropped as the Vietnam War continued - as most popular accounts suggest - then civilian and military actors alike would have engaged in less frequent political behaviors involving the military that violate the principles of civil-military relations. In particular, the theory suggests that there would have been fewer instances of civilian and military actors acting in ways to harness the prestige of the military in order to shape or influence public opinion by using or leveraging the military. While I do not doubt these predictions in a broad sense, I am not aware of any empirical work that has specifically looked at this case.  

Future scholarship should also more closely investigate the role of norm change and its potential influence in shaping civilian and military actor adherence to the principles of civil-military relations. This dissertation generally took a view that the dynamic of norm change was not strongly at work, and that polarization and military prestige were the variables that shaped civilian and military actor adherence to the principles of civil-military relations. 

But this dissertation did not thoroughly explore the possibility that polarization and military prestige are variables that shape the norms that civilian and military actors adopt and which subsequently impact adherence to the principles of civil-military relations. Future work might incorporate alternate methodological approaches than those undertaken here, including the use of interviews with current and former civilian and military elites, to better explore this possibility. 

Future research in this area would offer policymakers the opportunity to better evaluate how patterns of civil-military relations unfold in mature democracies over lengthy periods of time, and how one type of domestic environment perhaps impacts the behaviors undertaken by actors in another. For example, senior military officers who serve today in 2022, assuming they have served for 30-40 years, began their careers sometime between 1982 and 1992. These officers undoubtedly learned lessons and adopted habits (norms) of behavior as lieutenants and captains in the late 1980s - 1990s. This period happens to overlap with a period of time in which the prestige of the military increased after the Gulf War. 

As young officers, today's senior military leaders witnessed senior military leaders such as Colin Powell write op-eds and make public appeals about potential military involvement in the Balkans and other post-Cold War era crises. The question then becomes if and how the lessons these officers adopted - when they were young - then impacted the behaviors these officers have undertaken as the levels of polarization have increased throughout their careers. Through this line of investigation, what becomes important is not just variation in the level of polarization and/or military prestige, but rather the succession and the order of the types of domestic environments in which civilian and military actors operate. 

Finally, a major strand of future research should continue to unpack the relationship between political polarization and foreign policy, broadly speaking, and the military's role in this relationship. Scholars are certainly aware of and are investigating how polarization impacts a variety of foreign policy outcomes [@schultz_perils_2017; @myrick_external_2021]. But the role of the military, an actor that sits at the very intersection of foreign and domestic policy, remains one that is underdeveloped. Recent cases, to include the US withdrawal from Afghanistan and the current war between Russia and the Ukraine (and the role of the US military), stand out as cases that might assist scholars unpack this important strand of research. 

## Conclusion

The civilian and military actors who practice civil-military relations do so amid a broader context. This context is always changing as a result of domestic and international factors. This dissertation attempted to explain why and when civilian and military actors behave in ways that deviate from the central principles, or normative standards, of civil-military relations. This dissertation argued that the levels of political polarization and military prestige ultimately shape the conduct of civilian and military actors, and in unique ways. Scholars and practitioners now have at least a starting point to identify, measure, and assess civilian and military actor adherence to the principles of civil-military relations in mature democracies such as the United States.

\pagebreak










